### ISSUE TITLE
 open webeditor page with 404 error

### ISSUE THREAD

**Issue by SunRainBoat** [PistoiaHELM/HELMMonomerService#5]
After Installed HELMWebEditor ( hwe-1.1.0.zip ) , with HELM2MonomerService ( HELM2MonomerService.war ) and HELM2WebService ( WebService.war ),  when open webeditor page, we got error like this:
![image](https://user-images.githubusercontent.com/23480381/95710794-03993f00-0c94-11eb-90a8-044400ee4f97.png)
Here's detail info:
![image](https://user-images.githubusercontent.com/23480381/95710380-21b26f80-0c93-11eb-9b6c-091cda2a2888.png)
We notice web.xml file was missed in folder HELM2MonomerService/rest/WEB-INF/, is this correct or not?
![image](https://user-images.githubusercontent.com/23480381/95711011-73a7c500-0c94-11eb-8a2a-6a02c7cad7a6.png)

**Comment by ClairePA** [comment]
Hi, 
It is probably easiest to use the Docker package to ensure you have the right versions and all the files. Let me know if this works for you. 
https://github.com/PistoiaHELM/pistoiahelm.github.com/tree/master/docker

**Comment by EvaBt** [comment]
Hi,
according to the ReadMe file of HELMWebEditor the WebEditor would be available under "http://SERVER/HELM2MonomerService/hwe/", which worked for me locally. (http://localhost:8080/HELM2MonomerService/hwe/examples/App.htm)

**Comment by SunRainBoat** [comment]
> Hi,
> It is probably easiest to use the Docker package to ensure you have the right versions and all the files. Let me know if this works for you.
> https://github.com/PistoiaHELM/pistoiahelm.github.com/tree/master/docker

It works now, thank you:)

**Comment by ClairePA** [comment]
Great.
